# -*- coding: utf-8 -*-
"""K-Delivery, Speedy and Reliable — 본문 (YBM 김은형 공통영어2 Lesson 2)"""

TITLE_EN = "K-Delivery, Speedy and Reliable"
TITLE_KO = "K-배달, 신속하고 믿음직하다"

# (sid, 영어 문장, 한국어 해석)
S = [
 ("s1","In Korea, nearly anything can be delivered within twenty-four hours.","한국에서는, 거의 모든 것이 24시간 이내에 배달될 수 있다."),
 ("s2","Delivery is not limited to Korea; however, a unique culture has developed around the Korean delivery industry.","배달은 한국에만 국한된 것은 아니다. 그러나, 독특한 문화가 한국 배달 산업을 중심으로 발달하였다."),
 ("s3","People in Korea can order whatever they want whenever they want and have it delivered wherever they want.","한국에 있는 사람들은 그들이 원하는 때라면 언제든지 그들이 원하는 것이 무엇이든 주문할 수 있고, 그들이 원하는 곳이라면 어디든지 그것을 배달 받을 수 있다."),
 ("s4","Delivery apps rank stores by various standards: review scores, popularity, price, delivery fee, and distance, to name a few.","배달 애플리케이션은 다양한 기준으로 상점들의 순위를 매긴다. 예를 들자면, 후기 점수, 인기, 가격, 배달료, 그리고 거리 등."),
 ("s5","The speedy delivery of purchased items to your house is literally at the tips of your fingers.","구매한 물건이 당신의 집으로 빠르게 배달되는 것은 말 그대로 당신 손가락 끝에 달려 있다."),
 ("s6","What is the history behind this culture?","이 문화 이면의 역사는 무엇일까?"),
 ("s7","In 1768, Hwang Yun-seok, a scholar, made a diary entry after taking the gwageo, a public service entrance exam.","1768년에 학자인 황윤석은 관리 채용 시험인 과거에 응시한 후 일기 기록을 남겼다."),
 ("s8","He wrote that he and his friends had ordered a delivery of naengmyeon for lunch.","그는 그와 그의 친구들이 점심 식사로 냉면 배달을 시켰다고 썼다."),
 ("s9","Hwang's diary is the first historical document indicating Koreans have been delivering food for at least two and a half centuries.","황윤석의 일기는 한국인들이 최소한 두 세기 반 동안 음식을 배달해 왔음을 보여 주는 최초의 역사적 기록물이다."),
 ("s10","During the Joseon period, specialized people called jeonin delivered letters for a fee.","조선 시대 동안, 전인이라고 불리는 전문화된 사람들이 돈을 받고 편지를 배달했다."),
 ("s11","In the days before the modern address systems, letters were delivered by name and place of residence, so a jeonin had to know the local areas like the back of his hand.","현대 주소 시스템이 있기 이전 시대에 편지는 이름과 거주지에 따라 배달되었으므로 전인은 해당 지역을 매우 잘 알고 있어야만 했다."),
 ("s12","Service prices were determined by schedule and distance.","서비스 가격은 일정과 거리에 따라 결정되었다."),
 ("s13","During the Japanese colonial period, Seoul's streets were filled with delivery professionals called “messengers,” most working for a company named Yongdalsa.","일제 강점기 동안, 서울의 거리는 '메신저'라고 불리는 배달 전문인들로 가득 차 있었는데, 그들 대부분은 용달사라는 이름의 회사에서 일하고 있었다."),
 ("s14","Many used bikes to speed up delivery.","많은 이들이 배달 속도를 높이기 위해서 자전거를 사용했다."),
 ("s15","When customers contacted Yongdalsa, a messenger went to pick up the item and then delivered it.","고객들이 용달사에 연락을 취하면, 메신저가 물건을 가지러 와서는 그것을 배달했다."),
 ("s16","Delivery mistakes were rare.","배달 실수는 드물었다."),
 ("s17","Messengers were sometimes charged with carrying large bundles of cash, but they were unfailingly honest and accurate.","메신저들은 때때로 다량의 현금 배달을 담당하기도 했는데, 그들은 변함없이 정직하고 정확했다."),
 ("s18","Customers trusted the messengers so much that they often did not check the items they received.","고객들은 메신저를 매우 믿었기에 종종 그들이 받은 물품을 확인하지도 않았다."),
 ("s19","This messenger service was unique to Korea and was based on a culture of mutual trust and a hunger for speed.","이러한 메신저 서비스는 한국만의 독특한 것이었으며, 상호 간의 신뢰 문화와 속도에 대한 갈망에 기반한 것이었다."),
 ("s20","It is possible that this paved the way for modern motorcycle delivery.","이것이 현대의 오토바이 배달의 토대를 닦았을 가능성이 있다."),
 ("s21","After Korea's liberation from colonial rule, it was divided into two.","식민지 지배에서 한국이 해방된 후, 한국은 둘로 나뉘었다."),
 ("s22","Then came the Korean War (1950-1953).","그리고는 한국 전쟁(1950-1953)이 발발했다."),
 ("s23","During this series of upheavals, Korea's delivery system fell apart.","이 일련의 격변 동안, 한국의 배달 시스템은 무너졌다."),
 ("s24","It was during the 1960s that delivery services grew again thanks to urbanization.","도시화 덕분에 배달 산업이 다시 성장한 것은 1960년대 동안이었다."),
 ("s25","As economic development progressed, people flocked to urban areas, where labor became concentrated.","경제 발전이 진행됨에 따라, 사람들은 노동력이 집중되는 도시 지역으로 모여들었다."),
 ("s26","This boosted the demand for delivery services.","이것이 배달 서비스에 대한 수요를 촉진시켰다."),
 ("s27","Deliveries of newspapers and milk quickly became popular.","신문과 우유 배달이 빠르게 인기를 얻었다."),
 ("s28","During lunchtime, city centers were filled with restaurant workers delivering trays full of food, stacked on top of each other.","점심시간 동안, 도시 중심부는 음식이 가득 찬 차곡차곡 쌓아 올려진 쟁반을 배달하는 식당 직원들로 가득 찼다."),
 ("s29","In the late 1980s and 1990s, caterers delivered homemade lunches in cloth bags to urban offices and returned later to collect empty dishes.","1980년대 후반과 1990년대에는, 음식 공급자들이 보자기에 싼 집에서 만든 점심을 도시의 사무실로 배달하였고 나중에 빈 그릇을 가져가기 위해 돌아왔다."),
 ("s30","The delivery area grew rapidly.","배달 영역은 빠르게 성장했다."),
 ("s31","In 1992, taekbae service, an express home delivery service through which a person receives an ordered item in at least a day or two, was introduced.","1992년에는 주문한 물건을 최소 하루 또는 이틀 만에 받을 수 있는 신속 가정배달 서비스인 택배 서비스가 도입되었다."),
 ("s32","On the first day, there were just two deliveries.","첫날에는 고작 두 건의 배달이 있었다."),
 ("s33","Now, millions of items are delivered daily.","이제 매일 수백만 개의 물건들이 배달된다."),
 ("s34","On average, a South Korean uses taekbae sixty-five times per year.","평균적으로 한국인 한 명은 택배를 연간 65번 이용한다."),
 ("s35","It was the development of digital and information technology that enabled the remarkable growth of taekbae.","택배의 놀랄 만한 성장을 가능하게 해 준 것은 바로 디지털과 정보 기술의 발전이었다."),
 ("s36","Logistics automation, GPS maps, and mobile applications have extended the range and scale of delivery services while keeping prices reasonable.","물류 자동화, GPS 지도, 그리고 모바일 애플리케이션은 가격을 적절하게 유지하면서도 배달의 범위와 규모를 넓혀 주었다."),
 ("s37","The phenomenal growth of e-commerce has driven the need for delivery services.","전자 상거래의 놀랄 만한 성장이 배달 서비스의 필요를 이끌어 왔다."),
 ("s38","A rule of thumb for taekbae is next-day delivery; if a person orders something today, it should arrive tomorrow.","택배의 원칙은 익일 배송이다. 누군가 오늘 무언가를 주문하면 내일 도착해야 한다."),
 ("s39","Taekbae is changing so rapidly that now more and more items are delivered on the same day they are ordered.","택배는 매우 빠르게 변화하고 있어 이제는 점점 더 많은 물품들이 그것들이 주문된 당일에 배달되고 있다."),
 ("s40","It is also possible to choose a specific date and time for delivery.","또한, 배송을 위한 특정 날짜와 시간을 선택할 수도 있다."),
 ("s41","Taekbae services, beginning from foot-powered delivery, have grown by leaps and bounds thanks to advancements in technology.","발로 움직이는 배달에서 시작한 이래로, 택배 서비스는 기술의 발전 덕분에 비약적으로 성장했다."),
 ("s42","Moreover, the services will likely be developed further due to continuing technological upheavals.","게다가 계속되는 기술적 격변으로 인해 이 서비스는 더 발달할 것 같다."),
 ("s43","Drones and autonomous robots are being used to deliver items by logistics companies in foreign countries.","외국에서는 드론과 자동화 로봇들이 물류 회사에 의해 물건을 배달하기 위해 사용되고 있다."),
 ("s44","In Korea, companies are testing the possibility of using advanced equipment such as autonomous vehicles, delivery robots, and drones for deliveries.","한국에서는 기업들이 자율 주행차, 배달 로봇, 그리고 드론과 같은 진보한 장비를 배달에 사용할 수 있는 가능성을 시험해 보고 있다."),
 ("s45","It is fair to say that modern Korean life cannot function as it does without its delivery services.","현대 한국의 삶은 배달 서비스 없이는 지금처럼 기능할 수 없다고 말해도 과언이 아니다."),
 ("s46","To maintain trust with customers, the Korean delivery industry prioritizes rapid, safe, and affordable transportation.","고객들과의 신뢰를 유지하기 위해, 한국 배달 산업은 빠르고, 안전하고, 적절한 가격의 운송을 최우선으로 삼고 있다."),
 ("s47","These persistent efforts for reliability and the adoption of advanced delivery technology will continue being the driving forces that will move Korean delivery forward well into the future.","이러한 신뢰를 위한 꾸준한 노력과 진보한 배달 기술의 도입은 한국 배달을 미래로 훨씬 나아가게 할 원동력이 될 것이다."),
]

# 문단 구분 (본문 탭 렌더링용)
PARAS = [
    ["s1","s2","s3","s4","s5","s6"],
    ["s7","s8","s9"],
    ["s10","s11","s12"],
    ["s13","s14","s15"],
    ["s16","s17","s18","s19","s20"],
    ["s21","s22","s23","s24","s25","s26","s27","s28","s29","s30"],
    ["s31","s32","s33","s34","s35","s36","s37","s38","s39","s40"],
    ["s41","s42","s43","s44"],
    ["s45","s46","s47"],
]

# 본문 빈칸 (sid, 빈칸으로 뚫을 단어[본문 표기 그대로], group)
# group: 같은 group은 서로 WORD BOX 오답으로 쓰지 않는다
BLANKS = [
 ("s1","within","PREP"),
 ("s2","limited","LIMIT"),
 ("s4","various","VARIED"),
 ("s5","speedy","SPEED"),
 ("s5","purchased","BUY"),
 ("s7","scholar","PERSON"),
 ("s7","entry","RECORD"),
 ("s9","historical","TIME"),
 ("s9","indicating","SHOW"),
 ("s11","residence","PLACE"),
 ("s11","local","PLACE"),
 ("s12","determined","DECIDE"),
 ("s13","colonial","TIME"),
 ("s13","professionals","PERSON"),
 ("s14","speed","SPEED"),
 ("s16","rare","SPECIAL"),
 ("s17","bundles","THING"),
 ("s17","unfailingly","MANNER"),
 ("s17","accurate","HONEST"),
 ("s18","received","GET"),
 ("s19","mutual","MUTUAL"),
 ("s20","paved","FOUND"),
 ("s21","liberation","FREE"),
 ("s23","upheavals","CHAOS"),
 ("s24","urbanization","URBAN"),
 ("s25","flocked","GATHER"),
 ("s25","labor","WORK"),
 ("s26","boosted","GROW"),
 ("s28","trays","THING"),
 ("s29","caterers","PERSON"),
 ("s31","express","SPEED"),
 ("s33","daily","TIMEADV"),
 ("s35","enabled","ALLOW"),
 ("s35","remarkable","SPECIAL"),
 ("s36","automation","AUTO"),
 ("s36","scale","SIZE"),
 ("s36","reasonable","SENSE"),
 ("s37","phenomenal","SPECIAL"),
 ("s38","rule of thumb","RULE"),
 ("s39","rapidly","SPEED"),
 ("s40","specific","CLEAR"),
 ("s41","foot-powered","MANNER"),
 ("s41","advancements","GROW"),
 ("s42","further","DIST"),
 ("s43","autonomous","AUTO"),
 ("s44","possibility","POSS"),
 ("s44","advanced","GROW"),
 ("s45","fair","FAIRHON"),
 ("s45","function","FUNC"),
 ("s46","maintain","KEEP"),
 ("s46","prioritizes","FOCUS"),
 ("s46","affordable","PRICE"),
 ("s47","persistent","PERSIST"),
 ("s47","reliability","TRUST"),
 ("s47","adoption","ACCEPT"),
 ("s47","driving","FORCE"),
]
