# -*- coding: utf-8 -*-
"""송우고 2학기 Lesson 2 (YBM 김은형 공통영어2) 어휘 데이터"""

# ── 1) 단어 뜻 (L2 단어 전체, 3페이지) ─────────────────────────────
# (word, meaning, pos)  pos: n/v/adj/adv/phr
WORDS = [
    ("more and more", "점점 더 많은", "phr"),
    ("specific", "구체적인, 특정한", "adj"),
    ("foot-powered", "발로 작동하는", "adj"),
    ("by leaps and bounds", "비약적으로, 급격하게", "phr"),
    ("advancement", "발전, 승진", "n"),
    ("technology", "과학 기술", "n"),
    ("be likely to", "~할 것 같다, ~할 개연성이 있다", "phr"),
    ("further", "더 멀리에, 더 나아가", "adv"),
    ("due to", "~때문에", "phr"),
    ("autonomous", "자율적인, 자주적인", "adj"),
    ("logistics", "실행 계획, 물류 관리", "n"),
    ("possibility", "가능성, 기회", "n"),
    ("advanced", "선진의, 상급의, 후기의", "adj"),
    ("equipment", "장비, 설비", "n"),
    ("such as", "~와 같은", "phr"),
    ("vehicle", "탈것", "n"),
    ("fair", "공평한, 타당한, 상당한", "adj"),
    ("function", "기능; 작동하다", "n"),
    ("maintain", "유지하다, 지속하다", "v"),
    ("trust", "신뢰; 신뢰하다", "n"),
    ("prioritize", "우선시하다", "v"),
    ("rapid", "빠른", "adj"),
    ("affordable", "감당할 수 있는, 알맞은", "adj"),
    ("transportation", "교통 수단, 운송", "n"),
    ("persistent", "끈질긴, 오래 지속되는", "adj"),
    ("effort", "노력", "n"),
    ("reliability", "신뢰도", "n"),
    ("adoption", "입양, 채택", "n"),
    ("driving force", "원동력", "n"),
    ("forward", "앞쪽으로", "adv"),
    ("late", "늦은; 늦게", "adj"),
    ("caterer", "음식 공급자, 출장 연회 업체", "n"),
    ("cloth bag", "보자기", "n"),
    ("return", "돌아가다, 돌려주다; 돌아감", "v"),
    ("rapidly", "빨리", "adv"),
    ("express", "신속한", "adj"),
    ("introduce", "내놓다, 소개하다", "v"),
    ("million", "100만", "n"),
    ("daily", "매일, 나날이; 매일의", "adv"),
    ("on average", "평균적으로, 대체로", "phr"),
    ("enable", "~할 수 있게 하다", "v"),
    ("remarkable", "주목할 만한, 놀랄 만한", "adj"),
    ("growth", "성장, 증대", "n"),
    ("automation", "자동화", "n"),
    ("extend", "확대하다, 연장하다, (손을) 뻗다", "v"),
    ("range", "범위; (범위가) ~에서 …사이이다", "n"),
    ("scale", "규모, 등급, 저울, 비늘", "n"),
    ("reasonable", "합리적인, 적정한", "adj"),
    ("phenomenal", "경이적인, 자연 현상의", "adj"),
    ("e-commerce", "전자 상거래의", "n"),
    ("drive", "이끌다", "v"),
    ("need", "필요, 요구", "n"),
    ("rule of thumb", "원칙", "phr"),
    ("mistake", "실수", "n"),
    ("rare", "드문", "adj"),
    ("be charged with", "~을 담당하다, 책임을 맡다", "phr"),
    ("bundle", "묶음", "n"),
    ("unfailingly", "변함없이", "adv"),
    ("honest", "정직한, 솔직한", "adj"),
    ("accurate", "정확한", "adj"),
    ("receive", "받다", "v"),
    ("unique", "독특한, 유일한", "adj"),
    ("be based on", "~에 기초하다, 근거하다", "phr"),
    ("mutual", "상호 간의, 공동의", "adj"),
    ("hunger", "배고픔, 열망", "n"),
    ("pave the way for", "~의 토대를 닦다", "phr"),
    ("liberation", "해방, 석방", "n"),
    ("divide", "나누다", "v"),
    ("upheaval", "격변", "n"),
    ("fall apart", "무너지다, 산산조각나다", "phr"),
    ("thanks to", "~의 덕분에, ~때문에", "phr"),
    ("urbanization", "도시화", "n"),
    ("development", "발달, 성장, 개발", "n"),
    ("progress", "진전; 진행되다", "n"),
    ("flock to", "모이다", "phr"),
    ("urban", "도시의", "adj"),
    ("labor", "노동", "n"),
    ("concentrate", "집중하다", "v"),
    ("boost", "신장시키다, 북돋우다", "v"),
    ("tray", "쟁반, 얕은 상자", "n"),
    ("stack on", "쌓다", "phr"),
    ("scholar", "학자", "n"),
    ("diary", "일기", "n"),
    ("entry", "기록", "n"),
    ("public service", "공무, 관리", "n"),
    ("entrance exam", "채용시험", "n"),
    ("historical", "역사적, 역사학의", "adj"),
    ("document", "서류", "n"),
    ("indicate", "나타내다, 가리키다", "v"),
    ("at least", "적어도, 최소한", "phr"),
    ("century", "1세기", "n"),
    ("period", "기간, 시대", "n"),
    ("for a fee", "돈을 지불하여", "phr"),
    ("modern", "현대의, 최신의", "adj"),
    ("address", "주소, 연설; 연설하다", "n"),
    ("residence", "주택, 거주", "n"),
    ("local", "지역의", "adj"),
    ("know like the back of one's hand", "~를 손바닥 보듯 잘 알다", "phr"),
    ("price", "가격", "n"),
    ("determine", "결정하다, 결심하다", "v"),
    ("schedule", "일정", "n"),
    ("distance", "거리", "n"),
    ("colonial", "식민지의, 식민지 시대의", "adj"),
    ("be filled with", "~로 가득차다", "phr"),
    ("professionals", "전문인, 전문가", "n"),
    ("contact", "연락하다; 접촉, 연락", "v"),
    ("speed up", "속도를 높이다", "phr"),
    ("nearly", "거의", "adv"),
    ("delivery", "배달, 배송", "n"),
    ("within", "~이내에", "phr"),
    ("limited", "제한된", "adj"),
    ("culture", "문화", "n"),
    ("develop", "발달하다, 발전하다", "v"),
    ("industry", "산업", "n"),
    ("order", "주문하다; 주문", "v"),
    ("whatever", "무엇이든", "phr"),
    ("whenever", "언제든지", "phr"),
    ("wherever", "어디든지", "phr"),
    ("deliver", "배달하다", "v"),
    ("app", "애플리케이션, 앱", "n"),
    ("rank", "순위를 매기다", "v"),
    ("various", "다양한", "adj"),
    ("standard", "기준", "n"),
    ("review", "후기, 리뷰", "n"),
    ("score", "점수", "n"),
    ("popularity", "인기", "n"),
    ("fee", "요금", "n"),
    ("speedy", "빠른, 신속한", "adj"),
    ("purchased", "구매한", "adj"),
    ("literally", "말 그대로", "adv"),
]

# ── 2) 유의어 ───────────────────────────────────────────────────
# (단어, 단어뜻, 유의어, 유의어뜻, group)
# group: 같은 group끼리는 서로 오답 선지로 쓰지 않는다 (= 실제로 뜻이 겹치는 묶음)
SYN = [
    ("specific",      "구체적인",      "precise",       "분명한, 정밀한",   "PRECISE|SPECIAL"),
    ("advancement",   "발전",          "progress",      "진보",             "GROW"),
    ("autonomous",    "자율적인",      "independent",   "독립적인",         "INDEP"),
    ("possibility",   "가능성",        "likelihood",    "가능성",           "POSS"),
    ("indicate",      "나타내다, 가리키다", "demonstrate", "나타내다, 보여주다", "SHOW"),
    ("fair",          "공평한",        "impartial",     "공정한",           "FAIRHON"),
    ("maintain",      "유지하다",      "sustain",       "지속시키다",       "KEEP"),
    ("document",      "문서",          "record",        "기록",             "RECORD"),
    ("limited",       "제한된",        "restricted",    "한정된",           "LIMIT|SPECIAL"),
    ("rapid",         "빠른",          "fast",          "빠른",             "SPEED"),
    ("persistent",    "끈질긴",        "tenacious",     "완강한",           "PERSIST"),
    ("effort",        "노력",          "endeavor",      "노력",             "EFFORT"),
    ("deliver",       "배달하다",      "transport",     "수송하다",         "CARRY|SHOW"),
    ("adoption",      "채택",          "acceptance",    "수락, 승인",       "ACCEPT"),
    ("late",          "늦은",          "delayed",       "지연된",           "LATE"),
    ("various",       "다양한",        "diverse",       "다양한",           "VARIED"),
    ("rapidly",       "빨리",          "quickly",       "신속히",           "SPEED"),
    ("introduce",     "내놓다, 소개하다", "present",     "제시하다",         "SHOW"),
    ("enable",        "~할 수 있게 하다", "allow",       "허용하다",         "ALLOW"),
    ("growth",        "성장",          "development",   "발달, 성장",       "GROW"),
    ("extend",        "연장하다",      "prolong",       "연장하다",         "KEEP"),
    ("reasonable",    "합리적인",      "sensible",      "분별 있는",        "SENSE"),
    ("phenomenal",    "경이적인",      "extraordinary", "놀라운, 비범한",   "SPECIAL"),
    ("mistake",       "실수",          "blunder",       "실수",             "ERROR"),
    ("rare",          "드문",          "scarce",        "희귀한",           "SPECIAL|LIMIT"),
    ("honest",        "정직한",        "truthful",      "진실한",           "FAIRHON"),
    ("stack on",      "쌓다",          "pile",          "쌓다, 포개다",     "PILE"),
    ("entry",         "기록",          "log",           "일지, 기록",       "RECORD"),
    ("unique",        "독특한",        "distinctive",   "독특한",           "SPECIAL|PRECISE"),
    ("mutual",        "상호 간의",     "reciprocal",    "상호 간의",        "MUTUAL"),
    ("liberation",    "해방",          "freedom",       "자유",             "INDEP"),
    ("standard",      "기준",          "criterion",     "기준",             "STANDARD"),
    ("upheaval",      "격변",          "disruption",    "붕괴, 혼란",       "CHAOS"),
    ("fall apart",    "무너지다, 부서지다", "collapse",  "붕괴하다",         "CHAOS"),
    ("speedy",        "빠른",          "swift",         "신속한",           "SPEED"),
    ("development",   "발달",          "progress",      "발전",             "GROW"),
    ("urban",         "도시의",        "metropolitan",  "대도시의",         "URBAN"),
    ("concentrate",   "집중하다",      "focus",         "초점을 맞추다",    "FOCUS"),
    ("boost",         "신장시키다",    "enhance",       "향상시키다",       "GROW|SPEED"),
    ("determine",     "결정하다",      "decide",        "결정하다",         "DECIDE"),
    ("modern",        "현대의",        "contemporary",  "현대의",           "MODERN"),
    ("speed up",      "속도를 높이다", "accelerate",    "가속하다",         "SPEED"),
]

# ── 3) 반의어 ───────────────────────────────────────────────────
# (단어, 단어뜻, 반의어, 반의어뜻, group)
ANT = [
    ("forward",             "앞쪽으로",         "backward",       "뒤쪽으로",           "DIR|GROW|LENGTH"),
    ("express",             "신속한",           "slow",           "느린",               "SPEED"),
    ("local",               "지역의",           "global",         "세계적인",           "SCOPE"),
    ("colonial",            "식민지의",         "independent",    "독립적인",           "FREE"),
    ("flock to",            "모이다",           "scatter",        "흩어지다",           "DIVIDE|FOCUS"),
    ("unfailingly",         "변함없이",         "variably",       "가변적으로",         "CONST"),
    ("hunger",              "배고픔",           "fullness",       "배부름, 포만감",     "HUNGER"),
    ("labor",               "노동",             "leisure",        "여가",               "WORK"),
    ("specific",            "구체적인",         "vague",          "모호한",             "CLEAR|FAIRHON"),
    ("advancement",         "발전",             "decline",        "퇴보",               "GROW|ACCEPT"),
    ("further",             "더 나아간",        "nearer",         "더 가까운",          "LENGTH|DIR"),
    ("be likely to",        "~할 가능성이 있다", "be unlikely to", "~할 것 같지 않다",  "POSS"),
    ("possibility",         "가능성",           "impossibility",  "불가능",             "POSS"),
    ("advanced",            "선진의",           "primitive",      "원시적인",           "GROW"),
    ("fair",                "공평한",           "unfair",         "불공정한",           "FAIRHON"),
    ("function",            "기능하다",         "malfunction",    "제대로 작동하지 않다", "FUNC"),
    ("trust",               "신뢰하다",         "distrust",       "불신하다",           "TRUST"),
    ("prioritize",          "우선시하다",       "neglect",        "소홀히 하다",        "FOCUS"),
    ("limited",             "제한된",           "unlimited",      "제한되지 않은",      "LIMIT"),
    ("affordable",          "가격이 적당한",    "expensive",      "비싼",               "PRICE|REASON"),
    ("by leaps and bounds", "비약적으로",       "gradually",      "서서히",             "SPEED"),
    ("automation",          "자동화",           "manualization",  "수동화",             "AUTO"),
    ("reliability",         "신뢰도",           "unreliability",  "비신뢰성",           "TRUST"),
    ("adoption",            "채택",             "rejection",      "거부",               "ACCEPT"),
    ("urban",               "도시의",           "rural",          "시골의",             "URBAN"),
    ("rapidly",             "빨리",             "slowly",         "천천히",             "SPEED"),
    ("historical",          "역사적인",         "contemporary",   "현대의",             "TIME"),
    ("remarkable",          "주목할 만한",      "ordinary",       "평범한",             "SPECIAL"),
    ("extend",              "연장하다",         "shorten",        "단축하다",           "LENGTH"),
    ("reasonable",          "합리적인",         "unreasonable",   "비합리적인",         "REASON|FAIRHON|PRICE"),
    ("professionals",       "전문가",           "amateurs",       "비전문가",           "PRO"),
    ("at least",            "적어도",           "at most",        "최대",               "AMOUNT"),
    ("rare",                "드문",             "common",         "흔한",               "SPECIAL"),
    ("honest",              "정직한",           "dishonest",      "부정직한",           "FAIRHON"),
    ("accurate",            "정확한",           "inaccurate",     "부정확한",           "FAIRHON"),
    ("unique",              "독특한",           "common",         "흔한",               "SPECIAL"),
    ("mutual",              "상호 간의",        "individual",     "개별적인",           "MUTUAL"),
    ("liberation",          "해방",             "oppression",     "억압",               "FREE"),
    ("divide",              "나누다",           "unite",          "결합하다",           "DIVIDE"),
    ("concentrate",         "집중하다",         "distract",       "산만하게 하다",      "FOCUS"),
]

# ── 4) 목록 밖 오답 풀 (hard 모드) ───────────────────────────
# (영단어, 한글뜻, 품사, group)
# group이 출제 단어의 유의어/반의어 묶음과 겹치면 자동 제외되므로
# '그럴듯하지만 절대 정답은 아닌' 선지만 남는다.
EXT = [
    # 동사
    ("hesitate",    "망설이다",           "v", "X_DOUBT"),
    ("pretend",     "~인 척하다",         "v", "X_FAKE"),
    ("complain",    "불평하다",           "v", "X_BLAME"),
    ("betray",      "배신하다",           "v", "TRUST"),
    ("regulate",    "규제하다",           "v", "LIMIT"),
    ("endure",      "견디다",             "v", "KEEP"),
    ("blame",       "비난하다",           "v", "X_BLAME"),
    ("wander",      "돌아다니다",         "v", "X_MOVE"),
    ("compensate",  "보상하다",           "v", "X_PAY"),
    ("assume",      "가정하다, 추정하다", "v", "X_GUESS"),
    ("forgive",     "용서하다",           "v", "X_SORRY"),
    ("imitate",     "모방하다",           "v", "X_COPY"),
    ("suspect",     "의심하다",           "v", "TRUST"),
    ("interrupt",   "방해하다",           "v", "FOCUS"),
    ("negotiate",   "협상하다",           "v", "X_DEAL"),
    ("convince",    "설득하다",           "v", "X_PERSUADE"),
    # 형용사
    ("reluctant",   "꺼리는, 주저하는",   "adj","X_UNWILLING"),
    ("humble",      "겸손한",             "adj","X_HUMBLE"),
    ("stubborn",    "고집 센",            "adj","PERSIST"),
    ("fragile",     "부서지기 쉬운",      "adj","X_WEAK"),
    ("hollow",      "속이 빈",            "adj","X_EMPTY"),
    ("shallow",     "얕은",               "adj","X_DEPTH"),
    ("fierce",      "사나운, 격렬한",     "adj","X_FIERCE"),
    ("durable",     "내구성 있는",        "adj","PERSIST"),
    ("clumsy",      "서투른",             "adj","X_SKILL"),
    ("greedy",      "탐욕스러운",         "adj","X_GREED"),
    ("cautious",    "조심스러운",         "adj","X_DOUBT"),
    ("awkward",     "어색한",             "adj","X_SKILL"),
    ("vital",       "필수적인",           "adj","X_VITAL"),
    ("weary",       "지친",               "adj","X_TIRED"),
    ("guilty",      "죄책감이 드는",      "adj","X_BLAME"),
    ("vivid",       "생생한",             "adj","X_VIVID"),
    ("sincere",     "진심 어린",          "adj","FAIRHON"),
    ("brutal",      "잔인한",             "adj","X_FIERCE"),
    ("dense",       "밀집한, 빽빽한",     "adj","X_DENSE"),
    # 명사
    ("burden",      "부담, 짐",           "n",  "X_BURDEN"),
    ("shelter",     "은신처, 보호소",     "n",  "X_PLACE"),
    ("threat",      "위협",               "n",  "X_FEAR"),
    ("wisdom",      "지혜",               "n",  "X_MIND"),
    ("rumor",       "소문",               "n",  "X_TALK"),
    ("insult",      "모욕",               "n",  "X_BLAME"),
    ("privilege",   "특권",               "n",  "X_RIGHT"),
    ("obstacle",    "장애물",             "n",  "X_BLOCK"),
    ("sacrifice",   "희생",               "n",  "X_GIVE"),
    ("dispute",     "분쟁, 논쟁",         "n",  "X_CONFLICT"),
    ("shortage",    "부족",               "n",  "X_LACK|LIMIT"),
    ("boundary",    "경계",               "n",  "LIMIT"),
    ("remedy",      "치료법, 치료약",     "n",  "X_CURE"),
    ("virtue",      "미덕",               "n",  "X_MORAL"),
    ("famine",      "기근",               "n",  "HUNGER"),
    # 부사
    ("barely",      "간신히, 겨우",       "adv","X_AMOUNT"),
    ("deliberately","고의로, 일부러",     "adv","X_INTENT"),
    ("frequently",  "자주",               "adv","SPECIAL|CONST"),
    ("eventually",  "결국",               "adv","X_END"),
    ("thoroughly",  "철저히",             "adv","X_INTENT"),
    ("sincerely",   "진심으로",           "adv","FAIRHON"),
    ("abruptly",    "갑자기",             "adv","X_SUDDEN"),
]
